name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: yarn install --immutable
      - run: yarn workspace react-native-render-html test:ts
        name: Typescript Tests
      - run: yarn workspace react-native-render-html test:jest --coverage
        name: Jest Tests
      - run: yarn workspace react-native-render-html test:lint
        name: Linting Tests
      - run: yarn workspace react-native-render-html build
        name: Build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages
